name: Coba

on: [issues.opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: ./greet-issue
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
