name: Coba

on: [issues]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - uses: ./greet-issue
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
